### ISSUE TITLE
Error when I try to send the message on chat.

### ISSUE THREAD

**Issue by vibgy** [firebase/angularfire-seed#93]
Cannot call $add method on a destroyed $firebaseArray object

```
angular.js:11706 Error: Cannot call $add method on a destroyed $firebaseArray object
    at Object.FirebaseArray._assertNotDestroyed (angularfire.js:572)
    at Object.FirebaseArray.$add (angularfire.js:141)
    at Scope.$scope.addMessage (chat.js:10)
    at Array.$parseFunctionCall (angular.js:12474)
    at $parseStatements (angular.js:12242)
    at callback (angular.js:21700)
    at Scope.$eval (angular.js:14570)
    at Scope.$apply (angular.js:14669)
    at HTMLButtonElement.<anonymous> (angular.js:21705)
    at HTMLButtonElement.eventHandler (angular.js:3047)
```

**Comment by katowulf** [comment]
Hi @vibgy! Please provide a minimal repro and version info.

**Comment by vibgy** [comment]
Never mind. I'll close the issue. I had not configured the rules in
firebase console properly.

**Comment by samuleruizgero** [comment]
Error when I try to send from to Firebase
Cannot call $add method on a destroyed $firebaseArray object
`Error: permission_denied: Client doesn't have permission to access the desired data.
    at Error (native)
    at Ci.I (http://localhost:9000/bower_components/firebase/firebase.js:215:36)
    at Object.I (http://localhost:9000/bower_components/firebase/firebase.js:218:386)
    at http://localhost:9000/bower_components/firebase/firebase.js:183:3
    at Qh.h.Ld (http://localhost:9000/bower_components/firebase/firebase.js:188:104)
    at Eh.Ld (http://localhost:9000/bower_components/firebase/firebase.js:178:364)
    at vh.Kg (http://localhost:9000/bower_components/firebase/firebase.js:176:280)
    at yh (http://localhost:9000/bower_components/firebase/firebase.js:170:464)
    at WebSocket.La.onmessage (http://localhost:9000/bower_components/firebase/firebase.js:169:245)(anonymous function) @ angular.js:13236d.$$error @ angularfire.min.js:12(anonymous function) @ angularfire.min.js:12(anonymous function) @ angularfire.min.js:12Scope.$eval @ angular.js:16820Scope.$digest @ angular.js:16636(anonymous function) @ angular.js:16859completeOutstandingRequest @ angular.js:5804(anonymous function) @ angular.js:6081


angular.js:13236 Error: Cannot call $add method on a destroyed $firebaseArray object
    at Object.d._assertNotDestroyed (https://cdnjs.cloudflare.com/ajax/libs/angularFire/1.1.3/angularfire.min.js:12:5167)
    at Object.d.$add (https://cdnjs.cloudflare.com/ajax/libs/angularFire/1.1.3/angularfire.min.js:12:1986)
    at Scope.$scope.addSurvey (http://localhost:9000/scripts/controllers/profile.js:73:35)
    at fn (eval at <anonymous> (http://localhost:9000/bower_components/angular/angular.js:14086:15), <anonymous>:4:218)
    at expensiveCheckFn (http://localhost:9000/bower_components/angular/angular.js:15076:18)
    at callback (http://localhost:9000/bower_components/angular/angular.js:24546:17)
    at Scope.$eval (http://localhost:9000/bower_components/angular/angular.js:16820:28)
    at Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:16920:25)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/bower_components/angular/angular.js:24551:23)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:9000/bower_components/jquery/dist/jquery.js:4732:27)`

**Comment by katowulf** [comment]
Once you call $destroy, you can no longer use the object. That's entirely the point.

**Comment by Boasbabs** [comment]
Please does  anyone know how to  configured the rules in firebase console properly. I am also get this same error in my app. I dont understand why the $destroy is called or the firebase object is being destroyed.

**Comment by Boasbabs** [comment]
I had similar problems but i configured the rules in firebase console and it works properly
