### ISSUE TITLE
Packages Outdated and npm start won't work?

### ISSUE THREAD

**Issue by alteredorange** [firebase/angularfire-seed#94]
This seems like a great place to start, but I can't get it to work.  When i do npm install, i get a ton of warnings on peerDependecies (below) and when I run npm start it also throws a warning, says it stars, but nothing is served.  I'm running a digitalocean node.js droplet.

I also put the agularfire-seed file in /opt/ because I don't think it liked being in root? Is there a preferred place to put it?  Thanks for any help you can give, can't wait to get this working!

**NPM START ERRORS**
```
> angularfire-seed@1.0.0 prestart /opt/angularfire-seed
> npm install

npm WARN cannot run in wd angularfire-seed@1.0.0 bower install (wd=/opt/angularf                    ire-seed)

> angularfire-seed@1.0.0 start /opt/angularfire-seed
> http-server -a localhost -p 8000

Starting up http-server, serving ./ on port: 8000
Hit CTRL-C to stop the server
```

**NPM INSTALL ERRORS**
```
WARN engine karma@0.10.10: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"4                    .2.4","npm":"2.14.12"})
npm WARN peerDependencies The peer dependency karma-jasmine@~0.1.0 included from                     karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-requirejs@~0.2.0 included fr                    om karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-coffee-preprocessor@~0.1.0 i                    ncluded from karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-html2js-preprocessor@~0.1.0                     included from karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-chrome-launcher@~0.1.0 inclu                    ded from karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-firefox-launcher@~0.1.0 incl                    uded from karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-phantomjs-launcher@~0.1.0 in                    cluded from karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN peerDependencies The peer dependency karma-script-launcher@~0.1.0 inclu                    ded from karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN deprecated lodash@1.1.1: lodash@<2.0.0 is no longer maintained. Upgrade                     to lodash@^3.0.0
npm WARN optional dep failed, continuing fsevents@0.2.1
|
> ws@0.4.32 install /opt/angularfire-seed/node_modules/karma/node_modules/socket                    .io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/opt/angularfire-seed/node_modules/karma/node_modules/                    socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Leaving directory `/opt/angularfire-seed/node_modules/karma/node_modules/s                    ocket.io/node_modules/socket.io-client/node_modules/ws/build'
npm WARN peerDependencies The peer dependency requirejs@~2.1 included from karma                    -requirejs will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD                    ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it                     explicitly.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm a                    nd is now out of date with respect to npm
npm WARN cannot run in wd phantomjs@1.9.19 node install.js (wd=/opt/angularfire-                    seed/node_modules/karma-phantomjs-launcher/node_modules/phantomjs)
npm WARN cannot run in wd angularfire-seed@1.0.0 bower install (wd=/opt/angularf                    ire-seed)
```

**Comment by alteredorange** [comment]
Also, here's the log I got when I tried to run npm start --unsafe-perm
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angularfire-seed@1.0.0
6 verbose unsafe-perm in lifecycle true
7 info angularfire-seed@1.0.0 Failed to exec prestart script
8 verbose stack Error: angularfire-seed@1.0.0 prestart: `npm install`
8 verbose stack Exit status 1
8 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at EventEmitter.emit (events.js:172:7)
8 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
8 verbose stack     at emitTwo (events.js:87:13)
8 verbose stack     at ChildProcess.emit (events.js:172:7)
8 verbose stack     at maybeClose (internal/child_process.js:818:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose pkgid angularfire-seed@1.0.0
10 verbose cwd /opt/angularfire-seed
11 error Linux 3.13.0-71-generic
12 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--unsafe-perm"
13 error node v4.2.4
14 error npm  v2.14.12
15 error code ELIFECYCLE
16 error angularfire-seed@1.0.0 prestart: `npm install`
16 error Exit status 1
17 error Failed at the angularfire-seed@1.0.0 prestart script 'npm install'.
17 error This is most likely a problem with the angularfire-seed package,
17 error not with npm itself.
17 error Tell the author that this fails on your system:
17 error     npm install
17 error You can get their info via:
17 error     npm owner ls angularfire-seed
17 error There is likely additional logging output above.
18 verbose exit [ 1, true ]
```

**Comment by katowulf** [comment]
The errors mean exactly what they say. You have to utilize the supported versions until the seed is upgraded to support newer releases. Keep in mind that the `npm start` command is for local development, not deployment on your remote server. AngularFire-seed can be uploaded the same as static HTML and run remotely, once you have things working to your liking. 

You can either install the bower dependencies locally and then upload those, or install them remotely. But the npm deps are purely for development and don't need to be uploaded to your hosting environment.

If you're looking for a full build process, you should check out [generator-angularfire](https://github.com/firebase/generator-angularfire/) (also slightly behind on point releases).

**Comment by alteredorange** [comment]
Thanks for the heads up, I'm new to this :)
